LandD: try circleci recommended approach to coverage issue

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -195,24 +195,56 @@ jobs:
         command: |
           circleci tests glob "spec/**/*_spec.rb" | \
           circleci tests run --command="xargs bundle exec rspec --format progress --format RspecJunitFormatter -o /tmp/test-results/rspec/rspec.xml" --verbose --split-by=timings --timings-type=filename
+
+    #### BEGIN old config for coverage results collation
+    # - store_test_results:
+    #     path: /tmp/test-results/rspec
+
+    # - run:
+    #     name: Stash Coverage Results
+    #     command: |
+    #       mkdir coverage_results
+
+    #       # Only copy coverage if main run, not re-run
+    #       # if [ ${CIRCLE_WORKFLOW_ID} = ${CIRCLE_WORKFLOW_WORKSPACE_ID} ]
+    #       # then
+    #         # suppress error if no file exists (can occur if running only failed tests)
+    #         cp -R coverage/.resultset.json coverage_results/.resultset-${CIRCLE_NODE_INDEX}-unit.json 2>/dev/null || :
+    #       # fi
+
+    # - persist_to_workspace:
+    #     root: .
+    #     paths:
+    #       - coverage_results
+    #### END old config for coverage results collation
+
+
+    # For a rerun that succeeds, restore the coverage files from the failed run
+    - restore_cache:
+        key: coverage-{{.Revision}}-{{.Environment.CIRCLE_NODE_INDEX}}
+    # # Save the coverage for rerunning failed tests. CircleCI will skip saving if this revision key has already been saved.
+    - save_cache:
+        key: coverage-{{.Revision}}-{{.Environment.CIRCLE_NODE_INDEX}}
+        paths:
+          - coverage_results
+        when: always
+    # # Needed to rerun failed tests
     - store_test_results:
         path: /tmp/test-results/rspec
-
-    - run:
-        name: Stash Coverage Results
-        command: |
-          mkdir coverage_results
-
-          # Only copy coverage if main run, not re-run
-          if [ ${CIRCLE_WORKFLOW_ID} = ${CIRCLE_WORKFLOW_WORKSPACE_ID} ]
-          then
-            # suppress error if no file exists (can occur if running only failed tests)
-            cp -R coverage/.resultset.json coverage_results/.resultset-${CIRCLE_NODE_INDEX}-unit.json 2>/dev/null || :
-          fi
+        when: always
+    # # Upload coverage file html so we can show it includes all the tests (not just rerun)
     - persist_to_workspace:
         root: .
         paths:
           - coverage_results
+        when: always
+    # # - run:
+    # #     name: Save html coverage
+    # #     command: go tool cover -html=cover.out -o cover.html
+    # #     when: always
+    - store_artifacts:
+        path: coverage_results
+        when: always
 
   integration_tests:
     parallelism: 10
